Attribute VB_Name = "SelType"
Function GetSelTypeString(SelType As Integer) As String
'If SelType =    swSelNOTHING   Then    GetSelTypeString =
If SelType = swSelEDGES Then GetSelTypeString = "EDGE"
If SelType = swSelFACES Then GetSelTypeString = "FACE"
If SelType = swSelVERTICES Then GetSelTypeString = "VERTEX"
If SelType = swSelDATUMPLANES Then GetSelTypeString = "PLANE"
If SelType = swSelDATUMAXES Then GetSelTypeString = "AXIS"
If SelType = swSelDATUMPOINTS Then GetSelTypeString = "DATUMPOINT"
If SelType = swSelOLEITEMS Then GetSelTypeString = "OLEITEM"
If SelType = swSelATTRIBUTES Then GetSelTypeString = "ATTRIBUTE"
If SelType = swSelSKETCHES Then GetSelTypeString = "SKETCH"
If SelType = swSelSKETCHSEGS Then GetSelTypeString = "SKETCHSEGMENT"
If SelType = swSelSKETCHPOINTS Then GetSelTypeString = "SKETCHPOINT"
If SelType = swSelDRAWINGVIEWS Then GetSelTypeString = "DRAWINGVIEW"
If SelType = swSelGTOLS Then GetSelTypeString = "GTOL"
If SelType = swSelDIMENSIONS Then GetSelTypeString = "DIMENSION"
If SelType = swSelNOTES Then GetSelTypeString = "NOTE"
If SelType = swSelSECTIONLINES Then GetSelTypeString = "SECTIONLINE"
If SelType = swSelDETAILCIRCLES Then GetSelTypeString = "DETAILCIRCLE"
If SelType = swSelSECTIONTEXT Then GetSelTypeString = "SECTIONTEXT"
If SelType = swSelSHEETS Then GetSelTypeString = "SHEET"
If SelType = swSelCOMPONENTS Then GetSelTypeString = "COMPONENT"
If SelType = swSelMATES Then GetSelTypeString = "MATE"
If SelType = swSelBODYFEATURES Then GetSelTypeString = "BODYFEATURE"
If SelType = swSelREFCURVES Then GetSelTypeString = "REFCURVE"
If SelType = swSelEXTSKETCHSEGS Then GetSelTypeString = "EXTSKETCHSEGMENT"
If SelType = swSelEXTSKETCHPOINTS Then GetSelTypeString = "EXTSKETCHPOINT"
If SelType = swSelHELIX Then GetSelTypeString = "HELIX"
If SelType = swSelREFERENCECURVES Then GetSelTypeString = "REFERENCECURVES"
If SelType = swSelREFSURFACES Then GetSelTypeString = "REFSURFACE"
If SelType = swSelCENTERMARKS Then GetSelTypeString = "CENTERMARKS"
If SelType = swSelINCONTEXTFEAT Then GetSelTypeString = "INCONTEXTFEAT"
If SelType = swSelMATEGROUP Then GetSelTypeString = "MATEGROUP"
If SelType = swSelBREAKLINES Then GetSelTypeString = "BREAKLINE"
If SelType = swSelINCONTEXTFEATS Then GetSelTypeString = "INCONTEXTFEATS"
If SelType = swSelMATEGROUPS Then GetSelTypeString = "MATEGROUPS"
If SelType = swSelSKETCHTEXT Then GetSelTypeString = "SKETCHTEXT"
If SelType = swSelSFSYMBOLS Then GetSelTypeString = "SFSYMBOL"
If SelType = swSelDATUMTAGS Then GetSelTypeString = "DATUMTAG"
If SelType = swSelCOMPPATTERN Then GetSelTypeString = "COMPPATTERN"
If SelType = swSelWELDS Then GetSelTypeString = "WELD"
If SelType = swSelCTHREADS Then GetSelTypeString = "CTHREAD"
If SelType = swSelDTMTARGS Then GetSelTypeString = "DTMTARG"
If SelType = swSelPOINTREFS Then GetSelTypeString = "POINTREF"
If SelType = swSelDCABINETS Then GetSelTypeString = "DCABINET"
If SelType = swSelEXPLVIEWS Then GetSelTypeString = "EXPLODEDVIEWS"
If SelType = swSelEXPLSTEPS Then GetSelTypeString = "EXPLODESTEPS"
If SelType = swSelEXPLLINES Then GetSelTypeString = "EXPLODELINES"
If SelType = swSelSILHOUETTES Then GetSelTypeString = "SILHOUETTE"
If SelType = swSelCONFIGURATIONS Then GetSelTypeString = "CONFIGURATIONS"
'If SelType =    swSelOBJHANDLES    Then    GetSelTypeString =
If SelType = swSelARROWS Then GetSelTypeString = "VIEWARROW"
If SelType = swSelZONES Then GetSelTypeString = "ZONES"
If SelType = swSelREFEDGES Then GetSelTypeString = "REFERENCE-EDGE"
'If SelType =    swSelREFFACES  Then    GetSelTypeString =
'If SelType =    swSelREFSILHOUETTE Then    GetSelTypeString =
If SelType = swSelBOMS Then GetSelTypeString = "BOM"
If SelType = swSelEQNFOLDER Then GetSelTypeString = "EQNFOLDER"
If SelType = swSelSKETCHHATCH Then GetSelTypeString = "SKETCHHATCH"
If SelType = swSelIMPORTFOLDER Then GetSelTypeString = "IMPORTFOLDER"
If SelType = swSelVIEWERHYPERLINK Then GetSelTypeString = "HYPERLINK"
'If SelType =    swSelMIDPOINTS Then    GetSelTypeString =
If SelType = swSelCUSTOMSYMBOLS - Obsolete Then GetSelTypeString = "CUSTOMSYMBOL"
If SelType = swSelCOORDSYS Then GetSelTypeString = "COORDSYS"
If SelType = swSelDATUMLINES Then GetSelTypeString = "REFLINE"
'If SelType =    swSelROUTECURVES   Then    GetSelTypeString =
If SelType = swSelBOMTEMPS Then GetSelTypeString = "BOMTEMP"
If SelType = swSelROUTEPOINTS Then GetSelTypeString = "ROUTEPOINT"
If SelType = swSelCONNECTIONPOINTS Then GetSelTypeString = "CONNECTIONPOINT"
'If SelType =    swSelROUTESWEEPS   Then    GetSelTypeString =
If SelType = swSelPOSGROUP Then GetSelTypeString = "POSGROUP"
If SelType = swSelBROWSERITEM Then GetSelTypeString = "BROWSERITEM"
If SelType = swSelFABRICATEDROUTE Then GetSelTypeString = "ROUTEFABRICATED"
If SelType = swSelSKETCHPOINTFEAT Then GetSelTypeString = "SKETCHPOINTFEAT"
'If SelType =    swSelCOMPSDONTOVERRIDE  Then    GetSelTypeString =
If SelType = swSelLIGHTS Then GetSelTypeString = "LIGHTS"
'If SelType =    swSelWIREBODIES Then    GetSelTypeString =
If SelType = swSelSURFACEBODIES Then GetSelTypeString = "SURFACEBODY"
If SelType = swSelSOLIDBODIES Then GetSelTypeString = "SOLIDBODY"
If SelType = swSelFRAMEPOINT Then GetSelTypeString = "FRAMEPOINT"
'If SelType =    swSelSURFBODIESFIRST    Then    GetSelTypeString =
If SelType = swSelMANIPULATORS Then GetSelTypeString = "MANIPULATOR"
If SelType = swSelPICTUREBODIES Then GetSelTypeString = "PICTURE BODY"
'If SelType =    swSelSOLIDBODIESFIRST   Then    GetSelTypeString =
If SelType = swSelLEADERS Then GetSelTypeString = "LEADER"
If SelType = swSelSKETCHBITMAP Then GetSelTypeString = "SKETCHBITMAP"
If SelType = swSelDOWELSYMS Then GetSelTypeString = "DOWLELSYM"
If SelType = swSelEXTSKETCHTEXT Then GetSelTypeString = "EXTSKETCHTEXT"
If SelType = swSelBLOCKINST - Obsolete Then GetSelTypeString = "BLOCKINST"
If SelType = swSelFTRFOLDER Then GetSelTypeString = "FTRFOLDER"
If SelType = swSelSKETCHREGION Then GetSelTypeString = "SKETCHREGION"
If SelType = swSelSKETCHCONTOUR Then GetSelTypeString = "SKETCHCONTOUR"
If SelType = swSelBOMFEATURES Then GetSelTypeString = "BOMFEATURE"
If SelType = swSelANNOTATIONTABLES Then GetSelTypeString = "ANNOTATIONTABLES"
If SelType = swSelBLOCKDEF Then GetSelTypeString = "BLOCKDEF"
If SelType = swSelCENTERMARKSYMS Then GetSelTypeString = "CENTERMARKSYMS"
If SelType = swSelSIMULATION Then GetSelTypeString = "SIMULATION"
If SelType = swSelSIMELEMENT Then GetSelTypeString = "SIMULATION_ELEMENT"
If SelType = swSelCENTERLINES Then GetSelTypeString = "CENTERLINE"
If SelType = swSelHOLETABLEFEATS Then GetSelTypeString = "HOLETABLE"
If SelType = swSelHOLETABLEAXES Then GetSelTypeString = "HOLETABLEAXIS"
If SelType = swSelWELDMENT Then GetSelTypeString = "WELDMENT"
If SelType = swSelSUBWELDFOLDER Then GetSelTypeString = "SUBWELDMENT"
'If SelType =    swSelEXCLUDEMANIPULATORS    Then    GetSelTypeString =
If SelType = swSelREVISIONTABLE Then GetSelTypeString = "REVISIONTABLE"
If SelType = swSelSUBSKETCHINST Then GetSelTypeString = "SUBSKETCHINST"
If SelType = swSelWELDMENTTABLEFEATS Then GetSelTypeString = "WELDMENTTABLE"
If SelType = swSelBODYFOLDER Then GetSelTypeString = "BDYFOLDER"
If SelType = swSelREVISIONTABLEFEAT Then GetSelTypeString = "REVISIONTABLEFEAT"
'If SelType =    swSelSUBATOMFOLDER  Then    GetSelTypeString =
If SelType = swSelWELDBEADS3 Then GetSelTypeString = "WELDBEADS"
If SelType = swSelEMBEDLINKDOC Then GetSelTypeString = "EMBEDLINKDOC"
If SelType = swSelJOURNAL Then GetSelTypeString = "JOURNAL"
If SelType = swSelDOCSFOLDER Then GetSelTypeString = "DOCSFOLDER"
If SelType = swSelCOMMENTSFOLDER Then GetSelTypeString = "COMMENTSFOLDER"
If SelType = swSelCOMMENT Then GetSelTypeString = "COMMENT"
If SelType = swSelCAMERAS Then GetSelTypeString = "CAMERAS"
If SelType = swSelMATESUPPLEMENT Then GetSelTypeString = "MATESUPPLEMENT"
If SelType = swSelANNOTATIONVIEW Then GetSelTypeString = "ANNVIEW"
If SelType = swSelGENERALTABLEFEAT Then GetSelTypeString = "GENERALTABLEFEAT"
If SelType = swSelSUBSKETCHDEF Then GetSelTypeString = "SUBSKETCHDEF"
If SelType = swSelDISPLAYSTATE Then GetSelTypeString = "VISUALSTATE"
If SelType = swSelTITLEBLOCK Then GetSelTypeString = "TITLEBLOCK"
If SelType = swSelEVERYTHING Then GetSelTypeString = "EVERYTHING"
If SelType = swSelLOCATIONS Then GetSelTypeString = "LOCATIONS"
If SelType = swSelUNSUPPORTED Then GetSelTypeString = "UNSUPPORTED"
If SelType = swSelSWIFTANNOTATIONS Then GetSelTypeString = "SWIFTANN"
If SelType = swSelSWIFTFEATURES Then GetSelTypeString = "SWIFTFEATURE"
If SelType = swSelSWIFTSCHEMA Then GetSelTypeString = "SWIFTSCHEMA"
If SelType = swSelTITLEBLOCKTABLEFEAT Then GetSelTypeString = "TITLEBLOCKTABLEFEAT"
If SelType = swSelOBJGROUP Then GetSelTypeString = "OBJGROUP"
If SelType = swSelCOSMETICWELDS Then GetSelTypeString = "COSMETICWELDS"
If SelType = SwSelMAGNETICLINES Then GetSelTypeString = "MAGNETICLINES"
If SelType = swSelSELECTIONSETFOLDER Then GetSelTypeString = "SELECTIONSETFOLDER"
If SelType = swSelSELECTIONSETNODE Then GetSelTypeString = "SUBSELECTIONSETNODE"
If SelType = swSelPUNCHTABLEFEATS Then GetSelTypeString = "PUNCHTABLE"
If SelType = swSelHOLESERIES Then GetSelTypeString = "HOLESERIES"

End Function
